[book]
authors = ["David Thrane Christiansen"]
language = "en"
multilingual = false
src = "src"
title = "Functional Programming in Lean"

[build]

[preprocessor.leanexample]
command = "python -X utf8 scripts/example.py"

[preprocessor.commands]
command = "python -X utf8 scripts/projects.py"

[preprocessor.leanversion]
command = "python -X utf8 scripts/lean-version.py"

[output.html]
additional-css = ["custom.css"]

#[output.pandoc]
#command = "python -X utf8 ../../scripts/one-markdown.py"

[output.wordcount]
