# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.4
    
    - name: Setup elan toolchain on this build
      run: |
        curl -O --location https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh
        chmod u+x elan-init.sh
        ./elan-init.sh -y --default-toolchain none
        
    - name: Set elan paths
      run: |
        echo "$HOME/.elan/bin" >> $GITHUB_PATH

    - name: Install lean toolchain for this build
      run: |
        cd examples
        lean --version
        
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.18'

    - name: Install mdbook-wordcount
      uses: baptiste0928/cargo-install@v1
      with:
        crate: mdbook-wordcount
        version: latest

    - name: Build example code
      run: |
        cd examples
        lake build

    - name: Build book
      run: |
        cd functional-programming-lean
        mdbook build

    - name: Release bits if a new release tag is pushed
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
      if: ${{ startsWith(github.ref, 'refs/tags/rel') }}
      with:
        dir: functional-programming-lean/book/html
        branch: gh-pages
        repo: leanprover/functional_programming_in_lean/
        token: ${{ secrets.PUBLISH_GITHUB_TOKEN }}